Repository owncloud/files_pdfviewer, pull requests merged in 2020-12, with the labels that each got.

#227 Fix context menu entry
  js/previewplugin.js
Labels: 3 - To review

#229 [Tests-Only][CI] fix the starlark code for reduced ci after merge and sonarcloud
  .drone.star
  .gitignore
  sonar-project.properties
Labels: QA-team

#231 [Tests-Only][CI] fix sonarcloud reporting in CI
  .drone.star
  sonar-project.properties
Labels: QA-team

#233 Call the t l10n api for translate the file action's item
  js/previewplugin.js
Labels: 3 - To review

#235 [tests-only] Adjust phpstan.neon bootstrapFiles
  phpstan.neon
Labels: 3 - To review

#234 Show Notification if downloading pdf is forbidden
  .phan/config.php
  appinfo/routes.php
  js/previewplugin.js
  lib/Controller/DisplayController.php
  tests/unit/Controller/DisplayControllerTest.php
Labels: 3 - To review

#237 Enhance canDownload notification text
  js/previewplugin.js
Labels: 3 - To review

#239 [tests-only] Implement latest .drone.star as at 2020-12-22
  .drone.star
Labels: 3 - To review, QA-team
